name: Deploy Node.js App to EKS  # Workflow name

on:
  push:
    branches:
      - "main1"  # Trigger on push to main1 branch
  pull_request:
    branches:
      - "main1"  # Trigger on pull requests to main1 branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging  # Specify the environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.0'  # Specify the kubectl version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Access Key
          aws-region: ap-south-1  # AWS Region

      - name: Set up EKS kubeconfig
        run: |
          aws eks update-kubeconfig --name eks-dev-cluster --region ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2  # Login to Amazon ECR

      - name: Get commit hash
        id: get-commit-hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get timestamp
        id: get-timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}  # Amazon ECR registry
          ECR_REPOSITORY: server  # Your repository name in Amazon ECR
          COMMIT_HASH: ${{ env.COMMIT_HASH }}  # Commit hash
          TIMESTAMP: ${{ env.TIMESTAMP }}      # Timestamp
        run: |
          # Define the image tag without the extra colon (no colons in tag other than the one separating the repository and tag)
          IMAGE_TAG=staging-${COMMIT_HASH}-${TIMESTAMP}
          
          # Define the full image name
          FULL_IMAGE_NAME=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          
          # Build and tag the Docker image
          docker build -t ${FULL_IMAGE_NAME} .

          # Push the image to ECR
          docker push ${FULL_IMAGE_NAME}

      - name: Update Helm values.yaml with the latest image
        run: |
          IMAGE_TAG=staging-${{ env.COMMIT_HASH }}-${{ env.TIMESTAMP }}
          FULL_IMAGE_NAME=${{ steps.login-ecr.outputs.registry }}/server:${IMAGE_TAG}
          
          # Update the repository and tag in values.yaml
          sed -i "s|repository: .*|repository: ${FULL_IMAGE_NAME}|" helm-chart-server/values.yaml

      - name: Deploy to EKS using Helm
        run: |
          helm upgrade --install testing helm-chart-server --values helm-chart-server/values.yaml
